### ISSUE TITLE
Wasserstein distance using optimal transport not showing up in the documentation

### ISSUE THREAD

**Issue by lizliz** [TopologicalSignalProcessing/teaspoon#6]
We have a command for computing wasserstein distance using the optimal transport (`ot`) package. However, it doesn't show up in the documentation automatically. 

I haven't done a lot of testing and I can't remember if it wrote it as such, but I believe this will do any $p$ and $\infty$ (so bottleneck) distance.  If this is the case, we could remove dependency on Hera entirely.

**Comment by lizliz** [comment]
Forgot to mention this is the command `wassersteinDist` in `teaspoon.TDA.Distance`

**Comment by barnesd8** [comment]
I think we can remove Hera and either update using the ot package, or include the bottleneck from persim, but it can be an option in the wassersteinDist function.  Currently when setting q = np.inf, it computes chebyshev distance, but I am unable to get it to match the results from the persim bottleneck library or the prior example from Hera as well. 
<img width="853" alt="Screenshot 2023-01-02 at 2 07 25 PM" src="https://user-images.githubusercontent.com/28761771/210270577-769c51da-35d4-4025-bd5b-915f3822be08.png">
 I suspect the matching for computation of bottleneck is being done differently.  Screenshot attached.

**Comment by barnesd8** [comment]
This is resolved in the documentation and will use the persim package for bottleneck distance
